#!/bin/bash

echo -e '\033[31m系统:\033[0m' $(uname -s)
echo -e '\033[31m用户名:\033[0m' $(whoami)
echo -e '\033[31mShell:\033[0m' $SHELL
echo -e '\033[31m运行时间:\033[0m' $(uptime -p |awk -F' ' '{print $2,$3,$4,$5}')
echo -e '\033[31m包数量:\033[0m' $(dpkg -l |wc -l)
echo -e '\033[31m分辨率:\033[0m' $(xrandr|head -n 1 |awk -F, '{print $2}' |awk -F' ' '{print $2,$3,$4}')
echo -e '\033[31m磁盘:\033[0m' $(cat /proc/partitions |grep -w "sda" | awk -F' ' '{print $3}' |awk '{printf "%.1f",$1/1024/1024}') 'GB'
echo -e '\033[31m设备:\033[0m' $(hostname)
echo -e '\033[31m操作系统名称:\033[0m' $(lsb_release -sd |grep -v "^No LSB modules are available")
echo -e '\033[31m操作系统类型:\033[0m' $(uname -m)
echo -e '\033[31m发型版:\033[0m' $(lsb_release -si |grep -v "^No LSB modules are available")
echo -e '\033[31m核心版本:\033[0m' $(uname -r)
echo -e '\033[31m处理器:\033[0m'$(cat /proc/cpuinfo |grep "model name" |cut -f2 -d: |head -n 1) $(cat /proc/cpuinfo |grep "physical id"|uniq |wc -l)'C' $(grep 'core id' /proc/cpuinfo | sort -u |wc -l)'核' $(grep 'processor' /proc/cpuinfo |wc -l)'线程'
echo -e '\033[31m内存:\033[0m' $(cat /proc/meminfo |grep "MemTotal" |cut -f2 -d:|awk -F' ' '{print int($1)}' |awk '{printf "%.1f",$1/1024/1024}') 'GB'
echo -e '\033[31mGPU:\033[0m' $(lspci |grep -i vga | awk -F'00:02.0 VGA compatible controller: ' '{print $1,$2}')
echo -e '\033[31m主板:\033[0m' $(cat /sys/devices/virtual/dmi/id/board_vendor) $(cat /sys/devices/virtual/dmi/id/board_name)
#echo -e '\033[31mGTK-THEME:\033[0m' $(cat $HOME/.config/gtk-3.0/settings.ini |grep "gtk-theme-name" |cut -f2 -d: | awk -F= '{print $2}')
#echo -e '\033[31mGTK-ICON:\033[0m' $(cat $HOME/.config/gtk-3.0/settings.ini |grep "gtk-icon-theme-name" |cut -f2 -d: | awk -F= '{print $2}')
#echo -e '\033[31mWM-THEME:\033[0m' $(awk '/<theme>/ {while (getline n) {if (match(n, /<name>/)) {l=n; exit}}} END {split(l, a, "[<>]"); print a[3]}' "$HOME/.config/openbox/rc.xml")