#!/bin/bash

echo -e '系统：' $(uname -s)
echo -e '用户名：' $(whoami)
echo -e 'Shell：' $SHELL
echo -e '运行时间：' $(uptime -p |awk -F' ' '{print $2,$3,$4,$5}')
echo -e '包数量：' $(dpkg -l |wc -l)
echo -e '分辨率：' $(xrandr|head -n 1 |awk -F, '{print $2}' |awk -F' ' '{print $2,$3,$4}')
echo -e '磁盘：' $(cat /proc/partitions |grep -w "sda" | awk -F' ' '{print $3}' |awk '{printf "%.1f",$1/1024/1024}') 'GB'
echo -e '设备：' $(hostname)
echo -e '操作系统名称：' $(lsb_release -sd |grep -v "^No LSB modules are available")
echo -e '操作系统类型：' $(uname -m)
echo -e '发型版：' $(lsb_release -si |grep -v "^No LSB modules are available")
echo -e '核心版本：' $(uname -r)
echo -e '处理器：'$(cat /proc/cpuinfo |grep "model name" |cut -f2 -d: |head -n 1) $(cat /proc/cpuinfo |grep "physical id"|uniq |wc -l)'C' $(grep 'core id' /proc/cpuinfo | sort -u |wc -l)'核' $(grep 'processor' /proc/cpuinfo |wc -l)'线程'
echo -e '内存：' $(cat /proc/meminfo |grep "MemTotal" |cut -f2 -d:|awk -F' ' '{print int($1)}' |awk '{printf "%.1f",$1/1024/1024}') 'GB'
echo -e 'GPU：' $(lspci |grep -i vga | awk -F'00:02.0 VGA compatible controller: ' '{print $1,$2}')
echo -e '主板：' $(cat /sys/devices/virtual/dmi/id/board_vendor) $(cat /sys/devices/virtual/dmi/id/board_name)